contactus/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from django.views.generic import TemplateView
from .views import contactmail
# from base.views import AssignmentListView
urlpatterns = [
    url(r'^$', contactmail, name="form"),
    url(r'^thankyou/$', TemplateView.as_view(template_name='thankyou.html'), name='thankyou'),    
    
    ]
    

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import TemplateView 
from django.contrib.auth import views as auth_views
from django.conf import settings
from base.views import *
from accounts.views import *

# from base.views import AssignmentListView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
   	url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    #url(r'^blog/', include('blogging.urls', namespace="blog")), 
    url(r'^accounts/', include('accounts.urls', namespace="accounts")), 
    url(r'^samples/', include('samples.urls', namespace="samples")),
    url(r'^contactus/', include('contactus.urls', namespace="contact")),
    url(r'^services/', include('services.urls', namespace="services")),
    url(r'^neworder/', include('ordernow.urls', namespace="neworder")),
    url(r'^careers/', include('careers.urls', namespace="careers")),
    # url(r'^signup/$', signup, name='signup'),
    # url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
    # url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #         activate, name='activate'),
    # url(r'^login/$', auth_views.login, name='login'),
    # url(r'^logout/$', auth_views.logout,{'next_page': '/'}, name='logout'),
    
    #url(r'^order/send/$', frontmail ),
    url(r'^order/thankyou/$', TemplateView.as_view(template_name='thankyou.html'), name='thankyou'),
    url(r'^order/$', frontmail, name='order'),
    
    url(r'^thankyou/$', TemplateView.as_view(template_name='thankyou.html'), name='thankyou'),
    url(r'^aboutus/$', TemplateView.as_view(template_name='about.html'), name='aboutus'),
    
    #url(r'^test/$', TemplateView.as_view(template_name='test.html'), name='test'),
    
    url(r'^companypolicy/$', TemplateView.as_view(template_name='privacy.html'), name='companypolicy'),
    
    #url(r'^services/$', TemplateView.as_view(template_name='services.html'), name='services'),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    
 

contactus/models.py
from django.db import models

# Create your models here.

contactus/forms.py
from django import forms


class Contactform(forms.Form):
	name = forms.CharField(max_length="50")
	email	= forms.EmailField(max_length="254", help_text="Enter your email")
	feedback 	= forms.CharField(max_length="1000")


	

contactus/views.py
from django.shortcuts import render
from django.core.mail import EmailMessage
# Create your views here.
from django.urls import reverse
from .forms import Contactform
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.http import HttpResponseRedirect

def contactmail(request):
    if request.method == 'POST':
      form = Contactform(request.POST)
      if form.is_valid():
        name = form.cleaned_data['name']
        
        email = form.cleaned_data['email']
        # botcheck = form.cleaned_data['botcheck'].lower()
        feedback = form.cleaned_data['feedback']
        
        #message1 = "name:  "+  name+ "\n" + "country :  "  + country + "\n"  + "Related_to :  " + Related_to + "\n" + "email : " + email + "\nMessage: \t"  + Message
        subject = "Form Submission on AcademiaBuddy"
        message = render_to_string('c_template.html', {
            'name': name,
            
            'email': email,
            'feedback': feedback,
            
        })    
        send_mail(subject, message, email, ['academiabuddy@gmail.com'])

        return HttpResponseRedirect(reverse('contact:thankyou'))
    else:
        form = Contactform
    template_name="contact.html"
    return render(request, template_name, {'form': form ,})       

contactus/templates/c_template.html
{% autoescape off %}
Hi Divya

Contact Name:
{{ name }}

Email:  {{ email }}


feedback:  {{ feedback }}



{% endautoescape %}

contactus/templates/contact.html
{% extends 'base.html' %}
{% block title %} Contact {{ block.super }}{% endblock %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div id="band" class="container text-center font" style="padding-top: 150px" >
  <h3 class=" container font"><span style="color: red; font-size: 40px">A</span><span style="color: blue;font-size: 30px">cademia</span><span style="color: red ; font-size: 40px">B</span><span style="color: blue;font-size: 30px">uddy.com</span></h3>
  <p class="font"><em>We love our work. You will too.</em></p>
  <p class="container font"  style="font-size: 19px;text-align: justify;"><span style="color: red; font-size: 19px"> A</span><span style="color: #2b7bbf;font-size: 19px  ">cademia</span><span style="color: red ; font-size: 19px">B</span><span style="color: #2b7bbf;font-size: 19px">uddy,</span> is a premier global online writing and design company. 
    <br>The company boasts of expert writers and designers who have immense knowledge and skills in various fields.<br> The company understands that despite presence of several other online writing and design companies, all its existing and new clients are valued. <span style="color: red; font-size: 19px"> A</span><span style="color: #2b7bbf;font-size: 19px  ">cademia</span><span style="color: red ; font-size: 19px">B</span><span style="color: #2b7bbf;font-size: 19px">uddy,</span> is delighted to offer professional and a one-on-one online help and assistance to clients seeking various writing and design services. <b>Students, professionals, and researchers from various schools, colleges, and universities across the globe are invited to try our excellent online writing and design services. The company has a team of native writers and designers from the US, UK & Australia that help in preparing and delivering quality work. If you are not sure of where to get quality, timely, accurate, and affordable online writing and design services, come to <span style="color: red; font-size: 19px"> A</span><span style="color: #2b7bbf;font-size: 19px  ">cademia</span><span style="color: red ; font-size: 19px">B</span><span style="color: #2b7bbf;font-size: 19px">uddy,</span>.</b> If you are sure that <span style="color: red; font-size: 19px"> A</span><span style="color: #2b7bbf;font-size: 19px  ">cademia</span><span style="color: red ; font-size: 19px">B</span><span style="color: #2b7bbf;font-size: 19px">uddy,</span> is the best place to get quality, timely, accurate, and affordable online writing and design services, come again.   </p>
  <br>
 
<div id="tour" class="bg-1">
  <div class="container">
    <h3 class="text-center font" ><u>Our Offices</u></h3>
    <p class="text-center font" style="font-size: 30px">Lets us take best out of everything.<br><br></p>
    <ul class="list-group"> 
      <li class="list-group-item font" style="font-size: 20px;color: blue">UK &nbsp &nbsp  &nbsp &nbsp &nbsp<span class="label label-success">Active</span></li>
     
      <li class="list-group-item font" style="font-size: 20px;color: blue"> AUS &nbsp &nbsp<span class="label label-success">Active</span></li> 
    </ul>
    

<div id="contact" class="container" style="padding-top: 40px">
  <h3 class="text-center font" style="color: black;font-size: 25px" >Contact</h3>
  <p class="text-center" style="color: black;" ><em style="font-size: 22px">We'd like to hear from you.</em></p>
  
  <div class="row" style="padding-top: 50px;font-size: 22px">
    <div class="col-md-4 font" style="color: black;font-size:20px">
      <b>Give us your Feedback about <span style="color: red; font-size: 19px"> A</span><span style="color: #2b7bbf;font-size: 19px  ">cademia</span><span style="color: red ; font-size: 19px">B</span><span style="color: #2b7bbf;font-size: 19px">uddy,</span></p></b>
      <p style="color: black"><span class="glyphicon glyphicon-map-marker font" ></span>London UK</p>
      <p style="color: black"><span class="glyphicon glyphicon-phone font"></span>Phone: +44 5046565658</p>
      <p class="font" style="color: black"><span class="glyphicon glyphicon-envelope font" ></span >Email: info@academiabuddy.com</p>
    </div>
    <form  method="POST" >{% csrf_token %}
    <div class="col-md-8" >
      <div class="row" >
        <div class="col-sm-6 form-group" >
          <input class="form-control font " type="text" name="name" maxlength="50" required id="id_name" placeholder="Name">
        </div>
        <div class="col-sm-6 form-group">
          <input class="form-control font" type="email" name="email" maxlength="254" required id="id_email" placeholder="Email">
        </div>
      </div>
      <input class="form-control font"  type="text" name="feedback" maxlength="1000" required id="id_feedback"  placeholder="Your Query "></input>
      <br>
      <div class="row">
        <div class="col-md-12 form-group">
          <button class="btn pull-right font" type="submit">Send</button>
        </div>
      </div>
    </div></form>
  </div></div></div></div></div>
  <br><br><br><br><br><br>
  <hr>
{% endblock content %}

contactus/templates/thankyou.html
    {% extends "base.html" %}
    {% block title %}Contact Us - Thank You{% endblock title %}
    {% block content %}
      <h3 class="container text-center font" style="padding-top: 150px;font-size: 30px">Thank you.</h3>
      <p  class="container text-center font" style="font-size: 30px">We will get in touch with you soon!.</p>
      <p class="container text-center font " style="font-size: 30px; "><a href="{% url 'index'%}"  style="color: #16489f">Take me to the home</a></p>
    {% endblock content %}
  