accounts/urls.py
from django.conf.urls import url, include

from django.views.generic import TemplateView 
from django.contrib.auth import views as auth_views
from django.conf import settings
from .views import *
# from base.views import AssignmentListView
urlpatterns = [
    

    

    url(r'^signup/$', signup, name='signup'),
    url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            activate, name='activate'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout,{'next_page': '/'}, name='logout'),
    url(r'^thankyou/$', TemplateView.as_view(template_name='thankyou.html'), name='thankyou'),
    
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
]
 

careers/urls.py
from django.conf.urls import url
from .views import Career
from django.views.generic import TemplateView
# from base.views import AssignmentListView
urlpatterns = [
    
    url(r'^$', Career.as_view(), name='create'),
  	url(r'^thankyou/$', TemplateView.as_view(template_name="thanks.html"), name='thankyou'),
    ]
    
 

contactus/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from django.views.generic import TemplateView
from .views import contactmail
# from base.views import AssignmentListView
urlpatterns = [
    url(r'^$', contactmail, name="form"),
    url(r'^thankyou/$', TemplateView.as_view(template_name='thankyou.html'), name='thankyou'),    
    
    ]
    

samples/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import SampleListView, SampleDetailView


# from base.views import AssignmentListView
urlpatterns = [

   	url(r'^$', SampleListView.as_view(), name="list"),
    url(r'^(?P<slug>[\w-]+)/$', SampleDetailView.as_view(), name="detail"),
    ]
    
 

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import TemplateView 
from django.contrib.auth import views as auth_views
from django.conf import settings
from base.views import *
from accounts.views import *

# from base.views import AssignmentListView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
   	url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    #url(r'^blog/', include('blogging.urls', namespace="blog")), 
    url(r'^accounts/', include('accounts.urls', namespace="accounts")), 
    url(r'^samples/', include('samples.urls', namespace="samples")),
    url(r'^contactus/', include('contactus.urls', namespace="contact")),
    url(r'^services/', include('services.urls', namespace="services")),
    url(r'^neworder/', include('ordernow.urls', namespace="neworder")),
    url(r'^careers/', include('careers.urls', namespace="careers")),
    # url(r'^signup/$', signup, name='signup'),
    # url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
    # url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #         activate, name='activate'),
    # url(r'^login/$', auth_views.login, name='login'),
    # url(r'^logout/$', auth_views.logout,{'next_page': '/'}, name='logout'),
    
    #url(r'^order/send/$', frontmail ),
    url(r'^order/thankyou/$', TemplateView.as_view(template_name='thankyou.html'), name='thankyou'),
    url(r'^order/$', frontmail, name='order'),
    
    url(r'^thankyou/$', TemplateView.as_view(template_name='thankyou.html'), name='thankyou'),
    url(r'^aboutus/$', TemplateView.as_view(template_name='about.html'), name='aboutus'),
    
    #url(r'^test/$', TemplateView.as_view(template_name='test.html'), name='test'),
    
    url(r'^companypolicy/$', TemplateView.as_view(template_name='privacy.html'), name='companypolicy'),
    
    #url(r'^services/$', TemplateView.as_view(template_name='services.html'), name='services'),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    
 

templates/snippets/formtemplate.html
{% load static %}
{% load widget_tweaks %}

<form method="POST" novalidate class=" container " style="background-color: #3588b6">
  {% csrf_token %}

  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
  {% endif %}
<div class="container" >
    <div class="row" id="pwd-container">
 <div class="modal-body row">
    <div class="col-md-6" >
  {% for field in form.visible_fields %}
    
      {{ field.label_tag }}
</div>
      {% if form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    
  {% endfor %}</div></div></div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

templates/snippets/head.html
{% load static %}

    
   
    <head>
<meta charset="utf-8"/>
<title>Academia Buddy ! Content, Assignment Writing and Development Agency Worldwide</title>
<meta name="description" content="Academia Buddy is a global online service provider specialized in writing and design. We offer a range of services from Academic Writing, Content Writing, Assignment Writing, Graphic Design, Architectural Design, Web Design, Web Development, Medical Writing, Technical Writing, Research Project Writing, and Dissertation Writing."/>
<meta name="keywords" content="Academic Writing, Content Writing, Assignment Writing, Graphic Design, Architectural Design, Web Design, Web Development, Medical Writing, Technical Writing, Research Project Writing, and Dissertation Writing.">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1" name="viewport"/>

<meta content="We charge you less as our charges are less. Let us write for you.." name="description"/>
<meta content="Academia Buddy" name="author"/>
<meta name="google-site-verification" content="MvwTEWP1uHmKsJ50k7KodYN884Sf_YDr4x9QeMoaAKg" />
<link href="https://fonts.googleapis.com/css?family=Lato:300" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"><link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="{% static 'vendor/simple-line-icons/simple-line-icons.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'css/animate.css' %}" rel="stylesheet">
<link href="{% static 'vendor/swiper/css/swiper.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'css/layout.min.css' %}" rel="stylesheet" type="text/css"/>
<link rel="icon" type="image/png" href="{% static 'img/logo_icon.png' %}"/>
<link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">    
<script src="{% static 'js/jquerymin.js' %}"  type="text/javascript"></script> 

<!--script type="text/javascript" src="js/nagging-menu.js" charset="utf-8"></script--> 
<script src="{% static 'custom.js' %}" type="text/javascript"></script> 
<script src="{% static 'js/aslider.js' %}"></script>      

    </head>

templates/snippets/nav.html
{% load static %}
<!-- Start of Async Drift Code -->
<script>
"use strict";

!function() {
  var t = window.driftt = window.drift = window.driftt || [];
  if (!t.init) {
    if (t.invoked) return void (window.console && console.error && console.error("Drift snippet included twice."));
    t.invoked = !0, t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ], 
    t.factory = function(e) {
      return function() {
        var n = Array.prototype.slice.call(arguments);
        return n.unshift(e), t.push(n), t;
      };
    }, t.methods.forEach(function(e) {
      t[e] = t.factory(e);
    }), t.load = function(t) {
      var e = 3e5, n = Math.ceil(new Date() / e) * e, o = document.createElement("script");
      o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + n + "/" + t + ".js";
      var i = document.getElementsByTagName("script")[0];
      i.parentNode.insertBefore(o, i);
    };
  }
}();
drift.SNIPPET_VERSION = '0.3.1';
drift.load('6nre6ceci5ra');
</script>
<!-- End of Async Drift Code -->
          <header class="header navbar-fixed-top">
              <nav class="navbar" role="navigation">
                <div class="container font">
                      <div class="menu-container js_nav-item">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="toggle-icon"></span>
                        </button>

                          <div class="logo">
                            <a class="logo-wrap" href="#body">
                                <img class="logo-img logo-img-main" src="{% static 'img/academialogo.png' %}" alt="AcademiaBuddy">
                                <img class="logo-img logo-img-active" src="{% static 'img/academialogo.png' %}" alt="AcademiaBuddy">
                            </a>
                        </div>
                    </div>

                    <div class="collapse navbar-collapse nav-collapse">
<div class="menu-container font">
                            <ul class="nav navbar-nav navbar-nav-right">
                                <li class="js_nav-item nav-item font"><a class="nav-item-child nav-item-hover font" href="/" style="color: #000">Home <i class="fa fa-home"></i></a></li>
                                
                <li class="js_nav-item nav-item"><a class="nav-item-child nav-item-hover font" href="{% url 'services:list' %}" style="color: #000">Services</a></li>
                                <li class="js_nav-item nav-item font"><a class="nav-item-child font nav-item-hover font" href="{% url 'neworder:create' %}" style="color: #000"><span class="w3-tag w3-small  w3-red" style="transform:rotate(-9deg)">
  Order Now 
  </span></a></li><li class="js_nav-item nav-item"><a class="nav-item-child nav-item-hover font" href="{% url 'aboutus' %}" style="color: #000">About Us</a></li>
                
                <li class="js_nav-item nav-item font"><a class="nav-item-child nav-item-hover font" href="{% url 'samples:list' %}" style="color: #000">Samples <i class="fa fa-book"></i></a></li>
                <li class="js_nav-item nav-item font"><a class="nav-item-child nav-item-hover font" href="{% url 'careers:create' %}" style="color: #000">Careers</a></li>
                
                
                                
                                <li class="js_nav-item nav-item font"><a class="nav-item-child nav-item-hover font " href="{% url 'contact:form' %}" style="color: #000">Contact Us</a></li>
                                {% if user.is_authenticated %}<li style="padding-top: 15px"><a href="{% url 'accounts:logout' %}" ><button class="btn btn-default  "  type="button"  style="background-color: #46bbc9">Sign out
     </button></a></li>{% else %}<li style="padding-top: 30px">    
                                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" style="background-color: #46bbc9">Your Account <i class="fa fa-briefcase"></i>
     <span class="caret" style="color: red"></span></button>
      <ul class="dropdown-menu">
      
         <li ><a href="{% url 'accounts:login' %}" class="font container js_nav-item nav-item " style="color: #17bed2    ;font-size: 20px">Sign in <i class="fa fa-user"></i></a></li>
      <li><a href="{% url 'accounts:signup' %}" class="font container js_nav-item nav-item "  style="color: #17bed2;font-size: 20px">Sign up <i class="fa fa-bolt"></i></a></li>{% endif %}
      
               </ul></li>
                               
              </ul>
            </div>
          </div>
        </div>
      </nav></header>         
                        
                            
                  