accounts/urls.py
from django.conf.urls import url, include

from django.views.generic import TemplateView 
from django.contrib.auth import views as auth_views
from django.conf import settings
from .views import *
# from base.views import AssignmentListView
urlpatterns = [
    

    

    url(r'^signup/$', signup, name='signup'),
    url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            activate, name='activate'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout,{'next_page': '/'}, name='logout'),
    url(r'^thankyou/$', TemplateView.as_view(template_name='thankyou.html'), name='thankyou'),
    
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
]
 

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import TemplateView 
from django.contrib.auth import views as auth_views
from django.conf import settings
from base.views import *
from accounts.views import *

# from base.views import AssignmentListView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
   	url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    #url(r'^blog/', include('blogging.urls', namespace="blog")), 
    url(r'^accounts/', include('accounts.urls', namespace="accounts")), 
    url(r'^samples/', include('samples.urls', namespace="samples")),
    url(r'^contactus/', include('contactus.urls', namespace="contact")),
    url(r'^services/', include('services.urls', namespace="services")),
    url(r'^neworder/', include('ordernow.urls', namespace="neworder")),
    url(r'^careers/', include('careers.urls', namespace="careers")),
    # url(r'^signup/$', signup, name='signup'),
    # url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
    # url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #         activate, name='activate'),
    # url(r'^login/$', auth_views.login, name='login'),
    # url(r'^logout/$', auth_views.logout,{'next_page': '/'}, name='logout'),
    
    #url(r'^order/send/$', frontmail ),
    url(r'^order/thankyou/$', TemplateView.as_view(template_name='thankyou.html'), name='thankyou'),
    url(r'^order/$', frontmail, name='order'),
    
    url(r'^thankyou/$', TemplateView.as_view(template_name='thankyou.html'), name='thankyou'),
    url(r'^aboutus/$', TemplateView.as_view(template_name='about.html'), name='aboutus'),
    
    #url(r'^test/$', TemplateView.as_view(template_name='test.html'), name='test'),
    
    url(r'^companypolicy/$', TemplateView.as_view(template_name='privacy.html'), name='companypolicy'),
    
    #url(r'^services/$', TemplateView.as_view(template_name='services.html'), name='services'),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    
 

accounts/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)
    # other fields...

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()	

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    full_name = forms.CharField(max_length=30, required=True, help_text='Only your first name')
    
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['full_name'].help_text = ''
        self.fields['password1'].help_text = ''
        self.fields['username'].help_text = ''
        self.fields['password2'].help_text = ''
        self.fields['email'].help_text = ''
    	

    class Meta:
        model = User
        fields = ('username', 'full_name',  'email', 'password1', 'password2', )

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string


from .forms import SignUpForm
from .tokens import account_activation_token

from django.core.urlresolvers import reverse
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate Your AcademiaBuddy Account'
            message = render_to_string('account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            return redirect(reverse('accounts:account_activation_sent'))
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

def account_activation_sent(request):
    return render(request, 'account_activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('/')
    else:
        return render(request, 'account_activation_invalid.html')

accounts/templates/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

Your AcademiaBuddy
{% endautoescape %}

accounts/templates/account_activation_sent.html
{% extends 'base.html' %}

{% block content %}
  <h3 class="container text-center font" style="padding-top: 150px;font-size: 30px">Thank you.</h3>
      <p  class="container text-center font" style="font-size: 30px">Hi! Thanks for using AcademiaBuddy. We have sent you a confirmation email to confirm your email id.</p>
      <p class="container text-center font " style="font-size: 30px; "><a href="{% url 'accounts:login'%}"  style="color: #16489f">Take me to login page</a></p>

<br><br><br><br><hr>
{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% block title %} Sign up for {{ block.super }}{% endblock %}


{% block content %}

{% load widget_tweaks %}
  <!-- <div class="container" style="padding-top:30px;">
    <div class="row" id="pwd-container">
   <div class="modal-body row">
    <div class="col-md-6">
      <form class="form-signin" method="post"  role='form' style="padding-top: 150px"> {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"  class="btn btn-lg btn-primary btn-block font">Sign up</button>
      </form>
    </div>
    <div class="col-md-6" style="padding-bottom: 40px">
    <h1 class="container-fluid font text-center font" style="padding-top: 200px">or <a href="{% url 'accounts:login' %}"> Login</a></h1>
    </div></div></div></div>   -->
    
    <!-- <div class="six columns">
      <label for="exampleRecipientInput">Reason for contacting</label>
      <select class="u-full-width" id="exampleRecipientInput">
        <option value="Option 1">Questions</option>
        <option value="Option 2">Admiration</option>
        <option value="Option 3">Can I get your number?</option>
      </select>
    </div>
      </div>
      <label for="exampleMessage">Message</label>
      <textarea class="u-full-width" placeholder="Hi Dave …" id="exampleMessage"></textarea>
      <label class="example-send-yourself-copy">
    <input type="checkbox">
    <span class="label-body">Send a copy to yourself</span>
      </label>
      <input class="button-primary" value="Submit" type="submit"> -->
      <!-- <h2 class="form-signin-heading font">Sign up!</h2>
        <br>
        <input class="form-control input-lg font" type="text"   name="username" maxlength="150" autofocus  required id="id_username" placeholder="First Name">
        <br>
        <input class="form-control input-lg font" type="text"  name="first_name" maxlength="30"  required id="id_first_name" placeholder="Your Full Name"><br>
        
        <input class="form-control input-lg font" type="email"  name="email" maxlength="254"  required id="id_email" placeholder="Your email">
        <br>
      
        <input type="password"  class="form-control input-lg font"  name="password1" required id="id_password1" placeholder="Password"  >
      <br>
      
        <input type="password"  class="form-control input-lg font"  name="password2" required id="id_password2" placeholder="Type your password again"  >
        <div class="checkbox">
            
        </div>
        <button type="submit"  class="btn btn-lg btn-primary btn-block font">Sign up</button> -->
<form class="form-signin" method="post">{% csrf_token %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert" >
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}
<div class="container form-group" style="padding-top: 100px;"><h1 class="container text-center font">Sign up to access all the contents of Academia Buddy!</h1>
<div class="container" style="padding-top: 30px">

  <div class="row" id="pwd-container">
    <div class="col-md-4"></div>
    
    <div class="col-md-4">
      <section class="login-form">
{% for field in form.visible_fields %}
  
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}<br>
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control input-lg Write" %}
    {% endif %}

    {% if field.help_text %}
      {{ field.help_text }}
    {% endif %}
  
{% endfor %}<button type="submit" class="btn btn-lg btn-primary btn-block">Submit</button></div></div></div></section></form></div>
<br<br><br><br><hr>
{% endblock %}

accounts/templates/thankyou.html
    {% extends "base.html" %}
    {% block title %} Thank You {{ block.super }}{% endblock title %}
    {% block content %}
      <h3>Thank you.</h3>
      <p>Your email was sent and I will get back to you as soon as I can.</p>
      <p>Return <a href="/">home</a></p>
    {% endblock content %}
  